### ISSUE TITLE
Regression in 5f892017fe65c7b13fe745863e55c4bc51240ec3

### ISSUE THREAD

**Issue by z0rc** [mafredri/zsh-async#14]
I'm using zsh-async with https://github.com/PythonNut/zsh-autosuggestions (an async fork of official zsh-asug).

Recently I noticed, that the autosuggestions stopped to be ...well, suggested. I bisected this to commit 5f892017fe65c7b13fe745863e55c4bc51240ec3 here. I have a suspicion that this is partially related to my configuration, because I'm using non-default path for `$HISTFILE`. I checked the code and didn't find a way to preserve this part of my configuration for async worker, hence raising this issue.

**Comment by z0rc** [comment]
Also https://github.com/PythonNut/zsh-autosuggestions/commit/f1071f83758256abe6f28526d6ecdb78fdd0ea8e#commitcomment-16698853

**Comment by mafredri** [comment]
Hmm, `emulate -R zsh` does not reset `$HISTFILE`, as far as I can tell.

```console
❯ printit() { print $@ }
❯ HISTFILE=~/test_history
❯ print $HISTFILE
/Users/mafredri/test_history
❯ async_start_worker test
❯ async_job test 'print $HISTFILE'
❯ async_process_results test printit
print 0 /Users/mafredri/test_history 0.0077450275
```

A limitation of `zsh-async` has always been that the environment is "snapshotted" when the async worker is started, meaning any settings or variables set at this point are cloned, never to be updated again.

To work around this, I've recommended passing configuration to async jobs, e.g. in this case maybe `async_job my_worker _zsh_autosuggest_suggestion $BUFFER $HISTFILE`. These would then be available inside the async worker as `$1` and `$2`, respectively.

The `emulate -R zsh` is to guard against the async worker being in an unexpected state (e.g. through different zsh options being enabled), if a function requires specific options to be set, I'd recommend using `setopt localoptions my_option1 my_option2` inside the function being run.

I guess it could be argued that we should avoid resetting the environment, so that the async jobs are run in the same environment they were created, however, I do not think that is the root cause of this issue.

One recommendation I'd make is to delay starting the async worker until the first time zsh-asug is activated, e.g. through:

```zsh
if ! (( ASUG_INIT_DONE )); then
    ASUG_INIT_DONE=1
    async_start_worker suggest -u
    async_register_callback suggest _zsh_autosuggest_callback
fi
````

This ensures the environment is fully set up before cloning.

**Comment by mafredri** [comment]
I can reproduce what you're experiencing, due to the `emulate -R zsh`, however, the history is not completely empty and gives results that are a partial match for a history item. This leads me to believe that `_zsh_autosuggest_suggestion` is relying on some other zsh option to be set, which is not set by default.

**Comment by z0rc** [comment]
After further investigation I can confirm, that it works only partially.

cc @PythonNut

**Comment by mafredri** [comment]
I guess part of the problem is the option check inside `_zsh_autosuggest_suggestion ` (specifically `[[ -o extended_history ]]`). With `emulate -R zsh` this will be false even if you have it enabled. Could be worked around if passed as a parameter instead.

**Comment by mafredri** [comment]
@z0rc I'm pretty sure your issue could be "fixed" by setting `setopt extended_history` inside `_zsh_autosuggest_suggestion`.

**Comment by z0rc** [comment]
@mafredri woah, thanks for prompt response! Proposed "solution" works for me, I can redefine `_zsh_autosuggest_suggestion` in my dotfiles until @PythonNut comes with more universal solution.

**Comment by mafredri** [comment]
No problem, glad it works 😄 ! I guess `emulate -R zsh` should have been documented better (as a breaking change), but I think it's a good change since it catches issues sooner, rather than later. If a user changes his options during the runtime of the shell, the async job would not know of this. But when all settings must be passed as parameters, we can keep the async job up-to-date (so to speak) as well.

One thing I think could benefit @PythonNut's async branch is if we allowed updating the environment of the async worker (e.g. partially updating a variable for the history whenever a new history item is added). Maybe something like `async_job_sync` that runs functions inside the async worker without forking (child). Still, this would create a "cache" between your code in the worker and zsh's own history management, which might lead to complications.

**Comment by z0rc** [comment]
Closing issue per https://github.com/PythonNut/zsh-autosuggestions/commit/b8ba147e5bdd923dfb8903a77c16639dd4068feb
Thanks again for researching this case.

**Comment by PythonNut** [comment]
Whoops sorry! I just happened to notice this and fix it myself.
