### ISSUE TITLE
Noisy output when `printexitvalue` is enabled

### ISSUE THREAD

**Issue by landaire** [mafredri/zsh-async#5]
With `setopt printexitvalue`, I get `zsh: exit 1` printed every time my terminal resizes, as seen here:

<img width="1166" alt="screen shot 2016-05-20 at 14 54 47" src="https://cloud.githubusercontent.com/assets/1313522/15443154/da07df48-1e9a-11e6-8457-c2862f471e2c.png">

This has to do with `*WINCH` handling. Is there any way to silence this?

**Comment by mafredri** [comment]
It looks to me like you're using the `pure` prompt, do you really need `setopt printexitvalue` since the prompt indicates exit status through color?

If you're answer is no, there are a few options:

1. Upgrade to zsh 5.2. In more recent versions of zsh `async` uses zle to watch for changes so `async_process_results` is not called needlessly.
2. Change [async.zsh#L164](https://github.com/mafredri/zsh-async/blob/032703d9773381ee35db87601a88493c5b54d79c/async.zsh#L164) to `return 0`. A zero exit status does no print the exit value. The non-zero exit status is only really useful if a user wants to manually check the results of `async_process_results`.
3. I'll commit a change in just a moment that will resolve your issue, which means you can just update `async.zsh`.

**Comment by landaire** [comment]
> It looks to me like you're using the pure prompt, do you really need setopt printexitvalue since the prompt indicates exit status through color?

Sometimes I like seeing the exit code.

I can confirm the fix is working though, thank you very much!

**Comment by mafredri** [comment]
> Sometimes I like seeing the exit code.

Not judging, was just interested to know :)!

> I can confirm the fix is working though, thank you very much!

Great, and you're welcome!
